// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, title, subject)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, created_at, updated_at, subject
`

type CreateConversationParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Title   string      `json:"title"`
	Subject string      `json:"subject"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.UserID, arg.Title, arg.Subject)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, user_id, title, created_at, updated_at, subject FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
	)
	return i, err
}

const listConversationsByUser = `-- name: ListConversationsByUser :many
SELECT id, user_id, title, created_at, updated_at, subject FROM conversations WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListConversationsByUser(ctx context.Context, userID pgtype.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByUserAndSubject = `-- name: ListConversationsByUserAndSubject :many
SELECT id, user_id, title, created_at, updated_at, subject FROM conversations WHERE user_id = $1 AND subject = $2
ORDER BY updated_at DESC
`

type ListConversationsByUserAndSubjectParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Subject string      `json:"subject"`
}

func (q *Queries) ListConversationsByUserAndSubject(ctx context.Context, arg ListConversationsByUserAndSubjectParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByUserAndSubject, arg.UserID, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationSubject = `-- name: UpdateConversationSubject :one
UPDATE conversations SET subject = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, created_at, updated_at, subject
`

type UpdateConversationSubjectParams struct {
	ID      pgtype.UUID `json:"id"`
	Subject string      `json:"subject"`
}

func (q *Queries) UpdateConversationSubject(ctx context.Context, arg UpdateConversationSubjectParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationSubject, arg.ID, arg.Subject)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
	)
	return i, err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :one
UPDATE conversations SET title = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, created_at, updated_at, subject
`

type UpdateConversationTitleParams struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationTitle, arg.ID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subject,
	)
	return i, err
}
