// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (user_id, content, type, embedding, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, content, type, embedding, metadata, created_at
`

type CreateMemoryParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	Type      string             `json:"type"`
	Embedding pgvector_go.Vector `json:"embedding"`
	Metadata  []byte             `json:"metadata"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.UserID,
		arg.Content,
		arg.Type,
		arg.Embedding,
		arg.Metadata,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Type,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories WHERE id = $1 AND user_id = $2
`

type DeleteMemoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) error {
	_, err := q.db.Exec(ctx, deleteMemory, arg.ID, arg.UserID)
	return err
}

const listMemoriesByUser = `-- name: ListMemoriesByUser :many
SELECT id, user_id, content, type, embedding, metadata, created_at FROM memories WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMemoriesByUser(ctx context.Context, userID pgtype.UUID) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Type,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemoriesByEmbedding = `-- name: SearchMemoriesByEmbedding :many
SELECT id, user_id, content, type, embedding, metadata, created_at, 1 - (embedding <=> $2) AS similarity
FROM memories
WHERE user_id = $1 AND embedding IS NOT NULL
ORDER BY embedding <=> $2
LIMIT $3
`

type SearchMemoriesByEmbeddingParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Embedding pgvector_go.Vector `json:"embedding"`
	Limit     int32              `json:"limit"`
}

type SearchMemoriesByEmbeddingRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Content    string             `json:"content"`
	Type       string             `json:"type"`
	Embedding  pgvector_go.Vector `json:"embedding"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Similarity int32              `json:"similarity"`
}

func (q *Queries) SearchMemoriesByEmbedding(ctx context.Context, arg SearchMemoriesByEmbeddingParams) ([]SearchMemoriesByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchMemoriesByEmbedding, arg.UserID, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoriesByEmbeddingRow
	for rows.Next() {
		var i SearchMemoriesByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Type,
			&i.Embedding,
			&i.Metadata,
			&i.CreatedAt,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
