// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteConversation(ctx context.Context, id pgtype.UUID) error
	DeleteMemory(ctx context.Context, arg DeleteMemoryParams) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	GetConversationByID(ctx context.Context, id pgtype.UUID) (Conversation, error)
	GetRecentMessages(ctx context.Context, arg GetRecentMessagesParams) ([]Message, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListConversationsByUser(ctx context.Context, userID pgtype.UUID) ([]Conversation, error)
	ListConversationsByUserAndSubject(ctx context.Context, arg ListConversationsByUserAndSubjectParams) ([]Conversation, error)
	ListMemoriesByUser(ctx context.Context, userID pgtype.UUID) ([]Memory, error)
	ListMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) ([]Message, error)
	SearchMemoriesByEmbedding(ctx context.Context, arg SearchMemoriesByEmbeddingParams) ([]SearchMemoriesByEmbeddingRow, error)
	UpdateConversationSubject(ctx context.Context, arg UpdateConversationSubjectParams) (Conversation, error)
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (Conversation, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
